services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: push_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - db_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d

  php:
    build: ./api
    volumes:
      - ./api:/var/www/html
      - ./service-account.json:/var/www/html/app/service-account.json
    environment:
      DB_HOST: db
      DB_NAME: push_db
      DB_USER: user
      DB_PASS: password
      JWT_SECRET: your_jwt_secret_here  # Replace with a secure secret
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./api:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

volumes:
  db_data: